### ISSUE TITLE
Why is HVM is disabled for instance store?

### ISSUE THREAD

**Issue by jszwedko** [andsens/bootstrap-vz#200]
I was just wondering if there is more context around why `hvm` is specifically disabled when the volume backing is set to `s3`. I removed this conditional and was able to bootstrap a new `hvm` Jessie AMI with the `s3` backing using the `extlinux` bootloader and it booted fine. This was on the `wip-integration` branch.

See: https://github.com/andsens/bootstrap-vz/blob/wip-integration-testing/bootstrapvz/providers/ec2/__init__.py#L52

**Comment by andsens** [comment]
It doesn't work on the development branch IIRC. I just haven't gotten around to testing those images yet, but the integration testing branch contains a lot of fixes for jessie and everywhere else, so that's just great news that things are working now :-)

I'm using #101 to track the progress for this, so I'm closing this one.

**Comment by jszwedko** [comment]
Gotcha, thank you!
