### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by daveloyall** [andsens/bootstrap-vz#241]
This link is bad https://github.com/andsens/bootstrap-vz/blame/master/manifests/README.rst#L38 ..But I'm not sure how to fix it without building the docs. Is there any chance that this line is already correct but the deployed version of the docs is old?

**Comment by myhro** [comment]
Actually every hyperlink that relates to another section of the documentation in this page is broken. I'll take a look.

**Comment by myhro** [comment]
I couldn't fix it. I mean, the link you pointed is easy, as you just have to change `providers <../bootstrapvz/providers>` to `providers <../providers>`, but others like `commands <../bootstrapvz/plugins/commands>` I couldn't find out how to fix. I've even tried to add a few entries to [links_mapping][1] without success.

I suspect that this is somewhat related to b8b94c1, but I can't say for sure.

[1]: https://github.com/andsens/bootstrap-vz/blob/d1b63938e91569a6f39f3168161efb7c70e15b51/docs/transform_github_links.py#L25

**Comment by andsens** [comment]
Woops. Fixed.
I forgot to adjust the link transformation for the docs when I altered the manifest docs structure.

@daveloyall: When adding links to source code in issues you should refer to a specific commit hash rather than a branch. So: https://github.com/andsens/bootstrap-vz/blame/7f936e9ad876bb9ef5bab65c53edf7ad7ba6e811/manifests/README.rst#L38 instead of https://github.com/andsens/bootstrap-vz/blame/master/manifests/README.rst#L38

This way people can still see the original code that caused the issue years later without having to dig through the commit history. It's really easy to get that link, when viewing the code just press "y" and github will replace the branchname/tag in the url with a commit hash.

**Comment by myhro** [comment]
Thank you, Anders. I've also fixed [a last link that was broken][1], although I'm still seeing a lot of mentions to `modernizr.min.js`, even when the file is there:

    [myhro@leptok:~/Documents/Git/bootstrap-vz]$ wget --spider -e robots=off -r -p http://localhost:8080/ 2>&1 | grep '^http' | sort
    http://localhost:8080/api/base/_static/js/modernizr.min.js
    http://localhost:8080/api/common/_static/js/modernizr.min.js
    http://localhost:8080/api/common/tasks/_static/js/modernizr.min.js
    http://localhost:8080/api/_static/js/modernizr.min.js
    http://localhost:8080/developers/_static/js/modernizr.min.js
    http://localhost:8080/manifests/_static/js/modernizr.min.js
    http://localhost:8080/plugins/_static/js/modernizr.min.js
    http://localhost:8080/providers/_static/js/modernizr.min.js
    http://localhost:8080/testing/_static/js/modernizr.min.js
    [myhro@leptok:~/Documents/Git/bootstrap-vz]$ file docs/_build/html/_static/js/modernizr.min.js 
    docs/_build/html/_static/js/modernizr.min.js: HTML document, ASCII text, with very long lines

Maybe this is not relevant? :-)

About the `wget` invocation: [Simple way to find broken links with Wget][2]

[1]: https://github.com/andsens/bootstrap-vz/commit/b63d87c29031c819cceb9e167975633041c40edb
[2]: http://www.createdbypete.com/articles/simple-way-to-find-broken-links-with-wget/

**Comment by daveloyall** [comment]
@andsens Ah, that makes sense.  Thanks!
