### ISSUE TITLE
EC2 ami build should return AMI id

### ISSUE THREAD

**Issue by stumyp** [andsens/bootstrap-vz#271]
It would be very helpful if bootstrap-vz can return AMI id it just generated. 
Will help with automated builds. (Packer does it, but it is not well Debian aware ...)

**Comment by andsens** [comment]
Hm, that is actually a bit of a challenge. Right now. the logger echoes to stdout when it has info messages and to stderr when there are errors. Capturing the AMI Id, would be quite a hassle if you follow me :-)

I can see the need though. Maybe a plugin that outputs all the relevant information in the end, would solve the problem, but I think a simpler solution for you right now would be to invoke [the bootstrapping `run()` function](https://github.com/andsens/bootstrap-vz/blob/56703055790124fae51967e2cecaa625f6d0e53a/bootstrapvz/base/main.py#L86) manually and extract the necessary info from the bsinfo object that is returned.

**Comment by stumyp** [comment]
Honestly, I was looking at packer.io and thinking if it is possible to make it use deb-bootstrap and start using it instead, both tools are suboptimal  for automation, unfortunately (IMHO).

BTW: Had anyone tried using bootstrap in Jenkins ? I feel like it worth a separate issue, but I get different results if I create AMI in Jenkins interface (headless/dumb terminal mode) and in CLI directly.

**Comment by stumyp** [comment]
I'm not good at python, but I could try and get it working.

**Comment by andsens** [comment]
> both tools are suboptimal for automation, unfortunately (IMHO).

I don't know about packer.io, but bootstrap-vz certainly isn't. We do fully automated integration tests for a lot of manifests (ec2, virtualbox and docker), from manifest generation to instance bootup and everything in between. The main bootstrap-vz functions have been built with automation in mind, so you should be able to do exactly that. Check out the `tests/` folder in the repo for some inspiration - everything is documented and all the steps are explained.

**Comment by stumyp** [comment]
I like bootstrap-vz and would prefer it over other tools, at least because it is "the Debian way".
But for automation pipelines require more interaction from the tool, may be I'm doing it wrong :smile: 

for my tasks, I have changes in the AMI I want to deploy rapidly, preferably without human interaction,  
- feed the updated manifest
- test it (not possible at the moment, AFAIK)
- spit out exact error if there is any
- get result AMI name and pipe it to the next tool

**Comment by andsens** [comment]
With bootstrap-vz you can put a "check" behind every of those bullet points. Additionally you can [initiate the bootstrapping process remotely](https://github.com/andsens/bootstrap-vz/tree/72699d09c8d18fccb6f434023f33c92ca4ad94ca/bootstrapvz/remote) if your testing server is outside of AWS.

Take a look [here](https://github.com/andsens/bootstrap-vz/blob/72699d09c8d18fccb6f434023f33c92ca4ad94ca/tests/integration/tools/__init__.py#L12) and  [here](https://github.com/andsens/bootstrap-vz/blob/72699d09c8d18fccb6f434023f33c92ca4ad94ca/tests/integration/providers/ec2/__init__.py). All you want to do has already been done, because we want to integration test any changes to bootstrap-vz.  For you it'll mostly be a matter of copy & pasting :-)

**Comment by andsens** [comment]
I'm closing this one, since it can be implemented easily with a third-party plugin.
