### ISSUE TITLE
kernel boot option console=hvc0 specific to xen and not suitable for virtualbox ?

### ISSUE THREAD

**Issue by olberger** [andsens/bootstrap-vz#312]
Hi.

It seems https://github.com/andsens/bootstrap-vz/commit/608de63d3ed4a365d6409007805d73d1f2ea909a changed the default kernel boot option in order to redirect login to the xen console (?).

However, as discussed in https://lists.debian.org/debian-cloud/2016/04/msg00021.html I think it is the cause of booting issues with virtualbox+vagrant.

I'd suggest to change this to depend on the target platform

**Comment by myhro** [comment]
@olberger can please you confirm if the #321 merge fixed this issue as well?

**Comment by olberger** [comment]
I probably won't be able to test this very soon, but will complain for sure when I do if things aren't fixed. Sorry for not being able to help more right now.

**Comment by EmmanuelKasper** [comment]
Yes this fixes the issue, at the cost of losing standard boot ouput on the normal console, since you redirect it to a serial console.

GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0" would be better so you have boot messages on both VGA console ans serial 
for the record, this is what vmdeboostrap is doing.

**Comment by andsens** [comment]
Fixed :-)
