### ISSUE TITLE
Install on bare metal ?

### ISSUE THREAD

**Issue by rockandska** [andsens/bootstrap-vz#404]
Is there any plan to be able to install a manifest directly on bare metal with partitions created based on volumes in yaml ? (or maybe I missed how to do it)
Is there any plan to have one manifest and be able to specify the provider directly on command line without the need to have multiple manifest ?

It will be really great if we could generate the same image for different provider with only one manifest and install it on bare metal if needed :smile: 

Regards,

**Comment by andsens** [comment]
> Is there any plan to be able to install a manifest directly on bare metal with partitions created based on volumes in yaml ?

There is not. bootstrap-vz is targeted specifically towards virtualized environments. Bare metal machines are beyond the scope of the project.

> Is there any plan to have one manifest and be able to specify the provider directly on command line without the need to have multiple manifest ?

There is not, mostly because there are some provider specific settings that can't be abstracted away. However, check out [the integration test tools](https://github.com/andsens/bootstrap-vz/blob/4cb1065551cb905bc97eed08a07718f288a16e82/tests/system/manifests/__init__.py#L23) where we merge manifests from some standard snippets and then [pass the resulting manifest directly to the bootstrapping function](https://github.com/andsens/bootstrap-vz/blob/4cb1065551cb905bc97eed08a07718f288a16e82/tests/system/tools/__init__.py#L12-L35). You could do something similar, where the snippets are one big base manifest and a few provider specific stubs.
